### ISSUE TITLE
Translation state is always "up to date" 

### ISSUE THREAD

**Issue by quodo** [JoomFish/joomfish-2.5#10]
(From old thread: https://github.com/JoomFish/jf-future/pull/1)
**Quodo**
G - Translation state is always "up to date" (green check mark) even when there is no translation. 
Note: for 3rd party Content Element that I tried the State is correct: Translation does not exist (red ball) when it doesn't exist, etc.
**GeraintEdwards replied**
G. Not looked at this yet - hold this thought and keep reminding me ;)

**Comment by akempkens** [comment]
This might be an issue related to the way how the original and the translation is matched. We created copies in our own tables in the past. So if a 3rd party content element is used you will use the generic logic. Using a content you will use the new logic and this might not store the copies correctly.

**Comment by klas** [comment]
I hope I fixed this :) Please test - worked ok in my tests

http://github.com/JoomFish/jf-future/commit/ed81e9dbc3182d278fe1c0f3b865c474b717731b

**Comment by quodo** [comment]
Works for me on J!1.7.3: the translation state is showing the correct icon (and for my 3rd party Content Element it still works as well).
