### ISSUE TITLE
K2 breaks when module lang switch enabled

### ISSUE THREAD

**Issue by buildpress** [JoomFish/joomfish-2.5#100]
Hello,

When the language switcher module is enabled on a K2 page of the website it gives a HTTP-500 error.
The following is from the error.log:

[Tue Aug 28 20:41:43 2012] [error] [client 77.251.209.52] PHP Fatal error:  Class 'JCategories' not found in /var/www/clients/client2/web15/web/libraries/joomfish/route/jfroute.php on line 134
[Tue Aug 28 20:44:09 2012] [error] [client 77.251.209.52] PHP Fatal error:  Class 'JCategories' not found in /var/www/clients/client2/web15/web/libraries/joomfish/route/jfroute.php on line 134, referer: http://test.skileraar.info/index.php?option=com_kunena&view=entrypage&defaultmenu=100856&Itemid=100855&lang=nl

User & pass to check it out can be provided.
- Joomla 2.5.6
- JoomFish-jf-future-beta1-0-g2bce530

Jasper

**Comment by klas** [comment]
Hi, while it seems from the error it was on com_kunena page, it should be fixed now.

**Comment by ghost** [comment]
Fatal error: Call to a member function get() on a non-object in \libraries\joomfish\route\jfroute.php on line 136

I use : JoomFish-jf-future-beta1-1-g8b24e0e and K2_v2.5.7.

I don't understand what that doesn't works
