### ISSUE TITLE
Error when enable plugin joomfish core overrides with template shape5 corporate responsive

### ISSUE THREAD

**Issue by pacbrother** [JoomFish/joomfish-2.5#101]
Hi,

I installed jf-future following the installation instructions from the wiki and all requirements and got the following error:

 Fatal error: Cannot redeclare class JMenuSite in /home/nedaliby/public_html/jupgrade/includes/menu.php on line 136

Testing testing enable and disable plugins and templates I checked that the error only appears using Shape5 Corporate Responsive with the plugin Joomfish Core Overrides enabled.

Also I've looked at the Shape5 forum and found a post with the same problem and question. The awnser of Shape5 moderator was:

"You would need to contact Joomfish for this error"

Below is my system information:

PHP Built On    Linux austin.directrouter.com 2.6.18-308.11.1.el5 #1 SMP Tue Jul 10 08:48:43 EDT 2012 x86_64
Database Version    5.1.63-cll
Database Collation  utf8_general_ci
PHP Version     5.3.13
Web Server  Apache
WebServer to PHP Interface  cgi-fcgi
Joomla! Version     Joomla! 2.5.6 Stable [ Ember ] 19-June-2012 14:00 GMT
Joomla! Platform Version    Joomla Platform 11.4.0 Stable [ Brian Kernighan ] 03-Jan-2012 00:00 GMT
User Agent  Mozilla/5.0 (Windows NT 6.1; WOW64; rv:15.0) Gecko/20100101 Firefox/15.0 

Thanks in advance,
Bruno

**Comment by klas** [comment]
If you send me this template for testing I can take a look, won't be used for anything but this purpose - email it to klas.berlic at gmail.com . Hard to comment on this without having access to this template, it could be that instead of using joomla loader site menu is being hardlinked somewhere.

**Comment by pacbrother** [comment]
Thanks Klas, I sent you the template file via email.

**Comment by pacbrother** [comment]
Hi Klas, did you receive my email with the template attached?

**Comment by klas** [comment]
Hi,

yes I did, thnx - I will check,  just have to find the time :)

**Comment by klas** [comment]
Hi,

this is an error that can only be fixed on shape5 side,  they have hardcoded file includes everywhere (joomla has a loader for this purpose).

Actuall error is in templates/corporate_response/vertex/s5flex_menu/helpers.php,  line 41 > 

change

```
$path = $info->path.'/includes/menu.php';
if (file_exists($path)) {
require_once $path;
// Create a JPathway object
$classname  = 'JMenu'.ucfirst($client);
```

to

```
$path = $info->path.'/includes/menu.php';
$classname  = 'JMenu'.ucfirst($client);
if (file_exists($path)) {
if (!class_exists($classname)){
     require_once $path;
}
// Create a JPathway object
```

**Comment by klas** [comment]
Aa I am not a subscriber please contact shape5 people to fix this
