### ISSUE TITLE
JoomFish language selector module doesn't offer "All" for on which languages it will be visible

### ISSUE THREAD

**Issue by NikiDeskovic** [JoomFish/joomfish-2.5#102]
It only offers content languages, but when changed to All directly in database, everything works OK.
On jf-future-beta1-0-g2bce530.

**Comment by klas** [comment]
This is how Joomfish works - All is not a language and Joomfish need source language set. If you set an item to default language it will show in all languages except in those where translation is found.

**Comment by NikiDeskovic** [comment]
Well, that's OK for the all content elements, but not for the language selector. Language selector should be visible for all languages in my opinion.

**Comment by klas** [comment]
Modules are translatable too, so as with any content it also works so with modules including  JF languages selector - setting module to a default language means it will show on all languages unless there is a translation (e.g. you might have this modules title translated).

**Comment by NikiDeskovic** [comment]
Thanks Klas for explaining.

**Comment by rogersk** [comment]
this is not what some extensions expect. for example VirtueMart2 will bitch about it until you create dummy menu items in secondary languages, because it looks for aliases in All, or current language.
