### ISSUE TITLE
BUG Show Page Heading change crashes page/menu/website

### ISSUE THREAD

**Issue by Engelmann** [JoomFish/joomfish-2.5#110]
Hi, a little BUG REPORT.
I tested a translation on a menu, working fine. 
Then on the default page (type: Articles » Featured Articles) I wanted to change in "Page Display Options" the "Show Page Heading"  change to : NO, to remove the title of the page and then when I'm saving I'm got following error message : "Save failed with the following error: A menu should contain only one Default home".
The site crashes on default main page (without any language selection) and in the selected main language page (other language main pages still working with direct access).
To restore a working situation, I had to set both front pages to "Default Page" : no. Make change to both pages. Set back the first page to "Default Page" : yes. Go back to Joomfish translation of the Menu, even if it is set as translated, if I save it again, it finally works again.
I hope I was clear enough and that it could help.

**Comment by klas** [comment]
related to #122 - should be fixed now
