### ISSUE TITLE
Cobalt 7 Compatibility

### ISSUE THREAD

**Issue by Serhioromano** [JoomFish/joomfish-2.5#111]
I am developer of the Cobalt CCK. I have some questions. Does old JF XML files will be compatible with this new JF? What I mean can we change it to adopt or there is new method?

Can you consider to add Cobalt 7 support? We can help you to do anything you need to accomplish that.

**Comment by klas** [comment]
Hi, 

old XML files should be compatible - JF 2.5. only has an additional storage method (native - for extensions storing separate language tagged items), but storage method used in 1.5. is still used in parallel to the new one (is up to extension developer to decide which method to use).

**Comment by klas** [comment]
If you need something specific or something is not working let us know

**Comment by Serhioromano** [comment]
I do not want to use old method if it is supported just for compatibility.  If new method is recommended I would like to switch to new one. Or it is a different methods?

**Comment by klas** [comment]
Both will be supported in the future as they fit different usages, new method is just an additional option that was developed for better joomla core compatibility and speed, but it requires new item for each language which is not very convenient when you are dealing with items that have only small parts translatable (e.g. photogallery). 

Also new method is a bit complex to implement, beside xml content elements you would probably also need to implement translationobject and translationparameters (see library/joomfish for examples for core items)

**Comment by akempkens** [comment]
Hi,
with the very latest version of JoomFish 2.5 I implemented a way to use individual translatable Objects (Models). The cool thing about them is that you can even keep them in the path of your extension and just need to implement our Interface to make them working.

Check out the implementation for core menu and content files (/libraries/joomfish/contentelements/) - these are example implementations for the core files that work quite well.
