### ISSUE TITLE
JoomFish control panel takes a long time to load

### ISSUE THREAD

**Issue by joshas** [JoomFish/joomfish-2.5#112]
I had to wait for quite a bit for JoomFish panel to load and it ended up with empty overlay linking to administrator/index.php?option=com_joomfish&task=cpanel.usersplash&layout=usersplash&tmpl=component
Other JoomFish sections seems to work normally.
PHP 5.2.17
Joomla! 2.5.8

**Comment by klas** [comment]
This could be a problem related to news feed being displayed, it this happening constantly?

**Comment by akempkens** [comment]
Switch of the news feed in the configuration.
