### ISSUE TITLE
HTTPS issue with language selector module

### ISSUE THREAD

**Issue by alainroger** [JoomFish/joomfish-2.5#114]
Hi,

till now i have no issue (except the flag display) with JF under j2.5.8 in HTTP. However, under HTTPS, the module "language selector" raised an interesting thing.

if you use the display "flags and names" as ul/li display, all links are like "doubled" as following:
https://www.jtest.lochttps//www.jtest.loc/index.php?lang=fr

so 2x at the beginning there is "https://www.rogtek3.loc" :-(

in HTTP everything works well.

Alain

**Comment by alainroger** [comment]
ok so if i remove the $absolute at line 163 of the jroute.php file (\libraries\joomfish\route)
i have:
$routedurl      = JRoute::_($varstring, true, $uri->isSSL());

and in this case it works well under HTTPS and HTTP under j1.7.
I need to test it under j2.5.

**Comment by klas** [comment]
Please test if it works now
