### ISSUE TITLE
Migrate or Use J 1.5 Content Element

### ISSUE THREAD

**Issue by airtek** [JoomFish/joomfish-2.5#116]
Hi Guys,

I'm testing Joomfish beta and it seems to work well.

I have a question: 

there is a way to use the old joomla 1.5  content elements for work with some components like joomla estate agency?

there is a new format of the xml file?

Thanks a lot

Goodbye

**Comment by klas** [comment]
You can use old content elements, things are backward compatible, but this will only work if extension itself has not changed (if it uses the same translatable fields as in 1.5. )
