### ISSUE TITLE
Content Language Activation

### ISSUE THREAD

**Issue by seancarew** [JoomFish/joomfish-2.5#129]
I am having an issue within backend/content languages of Joomfish When I try to activate then 'apply' a new 'content' language, I get this error...

'An error occured while saving your languages.'

Trying to just 'save' gives me this error:

'Error Saving Languages:Array'

I was able to activate 1 additional language just after installation. None since.

However, I am able to install more content languages... unable to activate any additional languages.

System Information

Database Version 5.1.61-log
Database Collation utf8_general_ci
PHP Version 5.3.14
Web Server Apache/2.2
WebServer to PHP Interface apache2handler
Joomla! Version Joomla! 2.5.8 Stable [ Ember ] 8-November-2012 14:00 GMT
Joomla! Platform Version Joomla Platform 11.4.0 Stable [ Brian Kernighan ] 03-Jan-2012 00:00 GMT

Also, I have noticed the default language appears twice in the joomla content language interface/

![rocket---Administration](https://f.cloud.github.com/assets/36703/83892/ce364140-63f5-11e2-941f-2ff88fc371ef.png)

**Comment by klas** [comment]
I tried to reproduce this error, but I was unsuccessful. Please try deleting all content languages in joomla, then try activating them again in Joomfish. Also please install latest version from here https://github.com/JoomFish/jf-future/archive/master.zip

**Comment by seancarew** [comment]
I deleted all content languages.  Afterwards, I was only able to re-activate English (UK) in joomfish ... which means Spanish disappeared from joomla content language list.  English (UK) is back listed twice in content...

Do I understand correctly that I must uninstall joomfish 2.5.0 and install this latest?

**Comment by klas** [comment]
Hi, yes try installing github version. Can you provide admin access to your site so we can take a look?

**Comment by akempkens** [comment]
I have had this Isle before. It was related to the ID references between the Joomla language table and the Joomfish extended table.

Be careful removing the content languages in Joomfish or Joomla can result in translations being not linked to the correct language anymore. 

May be you try to modify the two tables _languages and _jf_languages_ext manually. They should have only the records you need with equal PK ids. 
There was a bug related storing languages in the ext so yes upgrading to the latest version makes sense.

**Comment by seancarew** [comment]
I appreciate the help - this is a sandbox, so not worth the trouble.

I would like to understand what I did wrong.  What causes this problem?  Deleting content languages or home menus, or templates?

**Comment by klas** [comment]
see my answer on #132 , it is the same issue
