### ISSUE TITLE
Cannot filter on (un)published translations: database error 'Unknown column 'ct.published'...

### ISSUE THREAD

**Issue by quodo** [JoomFish/joomfish-2.5#13]
Cannot filter on (un)published translations: database error 'Unknown column 'ct.published'...

**Reproduce error**
- Joomla 1.7.3: JoomFish > Translation
- Select Language (Dutch) and Content Element (Cateogories, Contents, Menus, or Modules)
- Select Translation Availability: (un)published
  
  Notes
  - Not all content elements work (that's for a different issue)
  - Not all content elements have the Translation Availability filter
  - My 3rd party Content Elements with the Translation Availability filter work fine.

**Result (when Debug off and System Error Reporting Default)**
No valid database connection: DB function failed with error number 1054
Unknown column 'ct.published' in 'where clause' SQL=SELECT c.id, ct.id AS jfc_id, c.title as title, ct.title as titleTranslation, c.title, ct.title AS jfc_title, c.title_alias, ct.title_alias AS jfc_title_alias, c.catid, ct.catid AS jfc_catid, c.alias, ct.alias AS jfc_alias, c.introtext, ct.introtext AS jfc_introtext, c.fulltext, ct.fulltext AS jfc_fulltext, c.images, ct.images AS jfc_images, c.metakey, ct.metakey AS jfc_metakey, c.metadesc, ct.metadesc AS jfc_metadesc, c.publish_up, ct.publish_up AS jfc_publish_up, c.publish_down, ct.publish_down AS jfc_publish_down, c.created, ct.created AS jfc_created, c.modified as modified_date, c.modified, ct.modified AS jfc_modified, c.checked_out as checked_out, c.checked_out, ct.checked_out AS jfc_checked_out, c.checked_out_time, ct.checked_out_time AS jfc_checked_out_time, c.attribs, ct.attribs AS jfc_attribs, ct.id as jfc_id, ct.state as published, ct.id as jfc_refid, '2010-06-11 05:30:30' as lastchanged FROM jos_content as c LEFT JOIN jos_jf_translationmap as tm ON tm.reference_id=c.id AND tm.reference_table='content' AND tm.language='nl-NL' LEFT JOIN jos_content as ct ON tm.translation_id=ct.id WHERE ct.published=1 AND c.state>=-1 AND c.language="*" LIMIT 0, 20

_The #__content table has no published entry._

**Result (when Debug is on and System Error Reporting is on Maximum)**
500 - An error has occurred.
JDatabaseMySQL::query: 1054 - Unknown column 'ct.published' in 'where clause' SQL=SELECT COUNT(distinct id) FROM jos_content as c LEFT JOIN jos_jf_translationmap as tm ON tm.reference_id=c.id AND tm.reference_table='content' AND tm.language='nl-NL' WHERE ct.published=1 AND c.state>=-1

This is the logged query at the bottom of the page (when Debug is on)
SELECT COUNT(distinct id)
  FROM jos_content as c
  LEFT JOIN jos_jf_translationmap as tm
  ON tm.reference_id=c.id
  AND tm.reference_table='content'
  AND tm.language='nl-NL'
  WHERE ct.published=1
  AND c.state>=-1

_There is no ct table, only a c._

(By the way, I noticed this when testing Klas' commit to fix issue #10, but the error was not caused by that commit, in a previous installation (where that commit wasn't applied) I got the same error)

**Comment by MStruller** [comment]
there is in content.xml
<published>published</published>
must change in
<published>state</published>
i make not an pull request, it is in the pull requst i have make 15.Jan but not as an single commit

**Comment by klas** [comment]
Thnx MStruller, couldn't directly cherry-pick this as it was not in a single commit

**Comment by quodo** [comment]
Sorry, this only changes the error message for me, it does not fix the issue.

**System details**
- Joomla 1.7.3 + Dutch language
- PHP 5.2.9, Database 5.1.33, Apache 2.2.11 (XAMPP on Windows), Mozilla Firefox
- JoomFish with commit 3762f7f (of course) 
  (1st try with upgrade method in manifest.xml, 2nd try by first uninstalling JoomFish and then reinstalling it; checked that the line <published>state</published> was in the content.xml content element)

**New error message**
JDatabaseMySQL::query: 1054 - Unknown column 'ct.state' in 'where clause' SQL=SELECT COUNT(distinct id) FROM jos_content as c LEFT JOIN jos_jf_translationmap as tm ON tm.reference_id=c.id AND tm.reference_table='content' AND tm.language='nl-NL' WHERE ct.state=1 AND c.state>=-1

Note that it now says `unknown column 'ct.state'` instead of `unknown column 'ct.published'`.

Can this be something to do with the "ct" instead of "c"?
The query that is logged is this one:
`SELECT COUNT(distinct id)
  FROM jos_content as c
  LEFT JOIN jos_jf_translationmap as tm
  ON tm.reference_id=c.id
  AND tm.reference_table='content'
  AND tm.language='nl-NL'
  WHERE ct.state=1
  AND c.state>=-1`
--> no ct except for ct.state

By the way, I get this error with four Content Elements, not only the Contents one:
- Categories
- Contents - commit only tries to fix this
- Menus
- Modules

**Comment by MStruller** [comment]
OK.
This error is produce in ContentElement.php in function countContentSQL
and an result from the TranslationFilter.php class translationPublishedFilter here we have on line 692 and line 697
'ct. ....' this must <strong>test</strong> to change in 'c. ....'
allways i can not make an pull request see above.

Where reopen this?

**Comment by quodo** [comment]
The lines with ct instead of c are
https://github.com/JoomFish/jf-future/blob/master/component/admin/models/TranslationFilter.php#L692
`$filter = "c." . $this->filterField . "=$this->filter_value";`
https://github.com/JoomFish/jf-future/blob/master/component/admin/models/TranslationFilter.php#L697
`$filter = " ( c." . $this->filterField . "=$this->filter_value AND tm.translation_id IS NOT NULL ) ";`
(I think those are the lines that MStruller mentions)

I'm unable to oversee if this is the only thing that has to be changed and to see if this is the proper way. However, I can confirm that by making these ct to c changes in these two lines the error is gone. For all four content elements. _By the way, I can make a new branch on my fork, base it on the current jf-future/master branch, commit the two tiny changes and push it to my fork, then make a pull request for only this change._

Probably a seperate issue is that all items are Published (must have something to do with that Published is renamed to State for some tables) and I'm unable to set them to Unpublished (just something I wanted to test and check in the Translation Availability filter). Shall I create a new issue for this?

I do see a reopen button, but with a message "You don't have permission to reopen this issue". My guess is that only the Organization Members (see https://github.com/JoomFish) can reopen an issue...

**Comment by MStruller** [comment]
This is what i mean.
But before you make an pull see in issues #15.

**Comment by klas** [comment]
Will recheck this - but the thing is it works ok for me.

**Comment by klas** [comment]
Reopening - actually this are 2 different issues - one with debug off (fixed with referenced commit) and another one with debug on as debug  seems to trigger additional queries

**Comment by klas** [comment]
@GeraintEdwards @akempkens please take a look if I approached this from the right side in the last commit - added a join to add missing content table (second instance) to make query compatible with not-count (Debug off) one (see first message in this thread).

**Comment by quodo** [comment]
Yes, now I can filter on (un)published translations!

Tried to reproduce the error
- Joomla 2.5.0: JoomFish > Translation
- Select Language (Dutch) and Content Element (Categories, Contents, Menus, or Modules)
- Select Translation Availability: (un)published

All work fine, with Joomla debug on and off.

Note
- My 3rd party Content Elements with the Translation Availability filter **still** works fine.

**Comment by MStruller** [comment]
I think this issues can close
