### ISSUE TITLE
TranslationFilter in content.xml

### ISSUE THREAD

**Issue by MStruller** [JoomFish/joomfish-2.5#15]
in content.xml there are three filters

<published>state</published>
<trash>state</trash>
<archive>state</archive>

all the filters have the same based field 'state'
and i think this can have curios results
in the query we can  have 'c.state = 1 AND c.state >= -1 AND c.state = 0' so the query will not have an corect result.

I think better use only another filter (named state) where we have all from FilterPublished and archive and trash
and one change Archived state changed from a value of -1 to +2 (see http://docs.joomla.org/What%27s_new_in_Joomla_1.6)

**Comment by MStruller** [comment]
Oh i see 'Filter published' is for 'Translation Availability'
but by work on 'native' the published is for 'content' in the #__content table not in the #__jf_content table

**Comment by klas** [comment]
Technically this is ok, but from UI standpoint having separate archive filter is questionable as this states are now unified in joomla UI
