### ISSUE TITLE
Translation Save and Save&Close button both redirect to translation overview

### ISSUE THREAD

**Issue by quodo** [JoomFish/joomfish-2.5#22]
**Issue**
Saving a translation with "Save" returns you to the Translation Overview just like "Save & Close" where it should return you to the translation (Edit page) itself.

**Probable cause**
In /JROOT/administrator/components/com_joomfish/joomfish.php on line 52 (https://github.com/JoomFish/jf-future/blob/master/component/admin/joomfish.php#L52) and further the $task is split when it is a pair like translate.apply or translate.save (e.g. when you want to save a translation using Save or Save & Close) via
`list($controllerName, $task) = explode('.', $cmd);`

This split $task (apply or save) is then used in line 83

`````` $controller->execute($task);```
and then used in function saveTranslation in /JROOT/administrator/components/com_joomfish/controllers/translate.php

However, on line 342 the $task is tested like this (https://github.com/JoomFish/jf-future/blob/master/component/admin/controllers/translate.php#L342):
```     if ($this->task == "translate.apply")```

**Fix**
I'll create a pull request to change this to
```     if ($this->task == "apply")```
(not today; if no one beats me to it :))

**Tested**
Joomla 2.5 + JoomFish of 30 jan. 2012
Backend > Components > JoomFish > Translation > [choose language and content element] > Edit an item and click "Save" (not "Save & Close")
``````

**Comment by klas** [comment]
Note that this only makes Save (apply) button work, not the actual task of applying

**Comment by quodo** [comment]
You are working hard! I just finished updating (pulling) all the latest commits (I thought) to start making a patch and then I saw this...

**Comment by klas** [comment]
thnx :)  There is new update related to this that should also make apply work properly.

Note that install procedure has changed, the whole package is now installed in one go from the root manifest.xml,  the same when uninstalling component - plugins/modules will also get removed. Should make testing much simpler. I'm currently testing by directly installing from git repo placed in separate folder under apache root, so that it can be reached from joomla installer.

**Comment by quodo** [comment]
Yes, apply works: redirects to the Edit page. :-)

One problem (if I may nag): you loose all your edit work if you for example forget to create a different alias, but that's not what this issue was about.

I noticed the brand new and well working installatioin procedure (see http://www.joomfish.net/forum/viewtopic.php?f=48&t=10770#p37721).

It works when you install the zip that you can download from Git, and it works if you install from directory right from the git repository on my disk. The only thing making testing even more easy would be the "upgrade" method in the manifest instead of the "install" method, but I guess you don't want to do that if a lot of files are moved around?
