### ISSUE TITLE
Saving and article with a "Read More" section removes the part after "Read More"

### ISSUE THREAD

**Issue by quodo** [JoomFish/joomfish-2.5#23]
Reproduce
- Translation: Language = Dutch, Content elements = Contents
- Select (from sample content) the article "Beginners", it has a Read More in the Article Text.
- Copy all fields, make them all identical except the Alias field (translate from beginners to beginners-nl, you need a unique alias) and if you wish change the title to Beginners NL to check that you actually see the translated article in the frontend. You need to keep the Read More line.
- Now the page is reloaded (with the working Save button), but the Translation no longer shows the part after the Read more line.
- However, the frontend article shows the entire text, and there is a read more link on the frontpage for this article.
- Now save the translation again
- In the frontend the part after what used to be the Read more is removed (ok, it's logical since it wasn't showing in the translation)

**Comment by quodo** [comment]
To me it seems that the intro- and fulltext just aren't tied together.

In the jos_content table the translated article has the correct text in "introtext" and the correct text in "fulltext". However, the edit page for the translation only shows the introtext. (And of course, when you save that, there no longer is a fulltext, e.g. the text after the readmore, in the table jos_content.)

**test**
I made a test article in the "main language" (english), it had text before and after the readmore and ID 70 in table jos_content. (prefix jos_ is used as GitHub Flavored Markdown uses the hash as a header).
The translated article in the "second language" (dutch) also had text before and after the readmore. It got ID 71 in table jos_content.

**possible location**
_In jf-future/admin/models/TranslationObject.php's function _loadContent 
`($this->contentElement->getTarget() == "joomfish")` is false, so you go to line 531, where on line 538 (https://github.com/JoomFish/jf-future/blob/master/admin/models/TranslationObject.php#L538) there is a commented block about the prehandlertranslation._

``` /*
    if ($field->prehandlertranslation != "")
    {
    if (method_exists($this, $field->prehandlertranslation))
    {
    $handler = $field->prehandlertranslation;
    $this->$handler($field, $translationFields);
    }
    } */
```

_that seems to me as if it should tie the intro- and fulltext together. However, $translationFields is uninitialised, so this block won't help._

**Comment by quodo** [comment]
Yes,  Klas' commit 0e0516bc9ecdf83f129e561ba6ab27a689f00fe is a big step forward. Most people will use this without any problems.

Now for some fine-tuning...

**Test scenario**
1 - Translate a text, but make sure you don't use an introtext. E.g.

```
<hr id="system-readmore" />
<p>Tekst</p>
```

with the editor toggled off and Save (Joomla allows this). (You can check the database, the content table does not have an introtext field).
2 - Now change your mind, and use some introtext. First toggle off the editor, then change the text e.g.

```
Some introtext.
<hr id="system-readmore" />
<p>Tekst (after readmore)</p>
```

(don't click the Toggle Editor button!) then click Save. 

**Problem 1**
This introtext won't save, database content table field introtext stays empty although there is a message "Translation saved".
However, if you enter the introtext in the editor, or if you toggle the editor back on before saving the text will be

```
<p>some tekst</p>
<hr id="system-readmore" />
<p>Tekst</p>
```

and the introtekst will be saved.
(editor used: TinyMCE that came with Joomla 2.5.1, User uses default and that is the default editor). 

**Problem 2**
Combine the described change from the test scenario with a change in the text after the readmore (the fulltext) in step 2, then the changes aren't saved (still no introtext and text after readmore doesn't save), although there is a message "Translation saved".

**Comment by klas** [comment]
hm, can't replicate this with Firefox, what browser are you using? What happens here is that editor automatically togles back to wysiwyg mode before save so text is enclosed in<p> tags.

**Comment by quodo** [comment]
Just tried it again with Mozilla Firefox 3.6.26 and Internet Explorer 8.0. Both have the same behavious, as described above.

This isn't a problem when I set the default Joomla editor to None instead of TinyMCE. And it only is a problem when TinyMCE is toggled off and I press Save then.

Could this "just" be a problem with the editor and not with JoomFish? How would I check it?

System Information:
PHP 5.2.9
Database MySQL 5.1.33
Apache 2.2.11 (on Windows: Xampp)
Joomla 2.5.1
User Agent Moziall/5.0 (when using Firefox 3.6.26)
Joomla Editor: TinyMCE (unless stated otherwise)

**Comment by klas** [comment]
Sorry, I replicated the issue after I commented, had to click enter after inserting text before readmore in step 2.

Should work now, it was javascript submit issue as function submitbutton was renamed/moved to variable Joomla.submit so all buttons were using default joomla funtion instead of joomfish override.

**Comment by quodo** [comment]
Yeah! I can't reproduce the error anymore :-) (in both Firefox 3.6 and Internet explorer 8)
As far as I can tell: this is solved.

How did you know where to look for this?

**Comment by klas** [comment]
Great! 

I'm a bug detective :))   Was easy after I found wrong values get posted.. took some time get to this point althou :)
