### ISSUE TITLE
new organisation in the models folder

### ISSUE THREAD

**Issue by MStruller** [JoomFish/joomfish-2.5#25]
based on Geraint changes for parameters (TranslateParams.php,TranslationObjectContent.php...) there are more files in the models folder and this files are not models in the classic mind
and its show there come more
so i think an new organisation for the folder models is need
as an referencepoint i have show on the JForm and JFields
there become in other components an folder in models (models/forms and models/fields)
so why not make the folders: 'com_joomfish/models/translate' , 'com_joomfish/models/translate/filters', com_joomfish/'models/translate/params', 'com_joomfish/models/translate/objects', 'com_joomfish/models/translate/filters', 'com_joomfish/models/translate/models', 'com_joomfish/models/translate/forms' ....
or create another path like 'com_joomfish/includes/' or 'com_joomfish/jfs/'

the contenelements in the old place, only the filters in contentelements go to the new path

**Comment by klas** [comment]
I think some reorganization is needed indeed, also refactoring and moving things around to get structure more MVC (e.g. a lot of stuff in controllers belong to views or models) and easier to follow , but at the same time I would say this should be a job for next major release

**Comment by klas** [comment]
A large portion of this files are now moved to libraries, this should make things a little better organized and easier to use via jimport.

**Comment by akempkens** [comment]
Ok I also finalized the loading of external translatable objects - based on this I consider this fixed
