### ISSUE TITLE
Remove usage of JParameter

### ISSUE THREAD

**Issue by akempkens** [JoomFish/joomfish-2.5#3]
Strict Standards: Declaration of JParameter::loadSetupFile() should be compatible with that of JRegistry::loadSetupFile() in /Daten/Work/Joomla/joomla.git/jake-cms/libraries/joomla/html/parameter.php on line 0 

This was actually already done by quodo but actually it seems that the changes have not been merged correctly. We need to verify this again with a specific pull request.

**Comment by klas** [comment]
Done, no issues, closing
