### ISSUE TITLE
[user error :(] Publishing a translated unpublished category "removes" the translation from the list

### ISSUE THREAD

**Issue by quodo** [JoomFish/joomfish-2.5#30]
On Joomla 2.5.1, with JoomFish "JoomFish-jf-future-3d7e33d":
Translate a category from the sample data, e.g. Sample Data-Banners (change title and alias, copy the empty description), leave it unpublished and click Save & Close. The translation will show up as unpublished in the Translation screen.

Now click the unpublished icon in the Translation screen (either in the row of Sample Data-Banners or select the row and click the toolbar-publish-button) with the intention to publish the translation. This, however, publishes the translation when you check it in the database, but the existance of the translation is not shown in the Translate screen. In the jos_categories table there is an entry for this new nl-NL category that is published.

A similar thing occurs when you translate menu items and then want to (un)publish them: the translation exists in the database table jos_menu, but is 'removed' from the translation view.

When I try to "redo" the translation you get a "Another menu item with the same parent has this alias" message. Not a surprise when you realise the translation already existed in the database and it's "just" not showing up.

**Comment by klas** [comment]
Hm, I just followed your test instructions and I'm not getting this result with latest version, item stays on the list. Perhaps you had Availabilty filter active?

**Comment by quodo** [comment]
My apologies. I do feel silly now... 
(Cannot reproduce this anymore, so it must have been the Availability filter. Explains why I had the same "problem" with Menus (has this filter) and not for example Banners (does not have this filter).
