### ISSUE TITLE
Default Home unique

### ISSUE THREAD

**Issue by alainroger** [JoomFish/joomfish-2.5#33]
Hi,

When i installed JoomFish-jf-future-3d7e33d.zip on Joomla 2.5.0 and tried to translate the main menu > HOME item, i get the following error message:
A menu should contain only one Default home.

there is no space for telling Joomla that this is the same item but in another language.

A.

**Comment by akempkens** [comment]
Actually there is the way Joomla uses itself. Seems we need to imitate this behavior to get around this warning. Good hint, thx

**Comment by MStruller** [comment]
Links for multilanguage help

http://www.rockettheme.com/forum/viewtopic.php?f=15&t=139340

here is the description why only one Home item
http://help.joomla.org/files/EN-GB_multilang_tutorial.pdf

**Comment by klas** [comment]
Note: solution not working yet

**Comment by caniggia** [comment]
I have better solution for it:

To work around this, go to translation and unpublish Your translation for default site menu. Then it comes again as default and You can publish it again.

Once You make any change in oryginal or translated default pages, You have to make above again, but first for sure setting oryginal as default, translated of curse then is not default, unpublish/publish translation and You are done:)

**Comment by klas** [comment]
This is solved after the above commit, which makes sure default is inserted in the copy even that joomla does not allow it by itself.

**Comment by alainroger** [comment]
Hi Guyz,

once again the problem of unique HOME came back on latest version of jf-future that i downloaded yesterday evening :(
