### ISSUE TITLE
Native translations: setting a language to default removes it from list

### ISSUE THREAD

**Issue by klas** [JoomFish/joomfish-2.5#38]
Setting a language of article, menu (elements using native translations) to default language removes it from list of items to translate, only items with "all languages" appear.

**Comment by MStruller** [comment]
Hello Klas,
i think this is more complexe see http://www.joomfish.net/forum/viewtopic.php?f=15&t=11011
i have make another way in my fork see https://github.com/MStruller/jf-future/tree/jformparameters
