### ISSUE TITLE
After (un)publishing a category translation it shows the translation as non-existant, however, it does exist

### ISSUE THREAD

**Issue by quodo** [JoomFish/joomfish-2.5#41]
Test case (on JoomFish 2.5 alpha aaaf802 on Joomla 2.5)
- Content element Categories, languages=dutch (my 2nd language in JF), reset all filters
- Translate category Plugins from sample data (set new title and alias, copy description, check publish and Save & Close). 
- Translation overview shows the translated title, a green checkmark (translation up to date) and the published icon. 
- In jos_jftranslationmap there now is a new entry with as reference_id the original article id and as translation_id the translated article id. 
- When I click the published icon to unpublish the translation the “translation up to date” icon changes as well: it’s now “translation does not exist”. 
  Note that in the jos_jf_translationmap table the entry has changed as well: the reference_id is now the same as the translation_id.

The other way around (start with an unpublished category and try to publish it) gives a similar result.
A similar thing happens for the modules and menus.

I would've expected the "reference_id" in the jos_jf_translationmap **not** to change.

**Comment by MStruller** [comment]
I think this issues can close

**Comment by quodo** [comment]
Thanks Klas, works like a charm and now I see your solution it seems so simple...
_(tried it with commits including a74ba2a as the last one)_
