### ISSUE TITLE
breadcrumbs wrongly rendered

### ISSUE THREAD

**Issue by data303** [JoomFish/joomfish-2.5#44]
I just installed the latest release of joomfish future. I created and translated one artice with joomfish. Setup is as follows: original language îs German. Other Language is English. When I switch from the origin article in German to the other language the "breadcrumbs" looks like this:

Original one (German language): zur Person > Lebenslauf (which is fine)
Translated one (English Language):  curriculum vitae > Uncategorised > curriculum vitae
Expteced entry should be: About myself > curriculum vitae

The whole rendering of the breadcrumb looks strange for me. It removes the first root item "zur Person" and adds an unexpected one "Uncategorised ".

It would be great if this could be fixed or described what can be done at configuration side that this is not happening.

Thank you

regards
data

**Comment by klas** [comment]
Reated to #55 as breadcrumbs are rendered from menus

**Comment by klas** [comment]
Fixed as sideeffect of #55 fixes
