### ISSUE TITLE
index3.php

### ISSUE THREAD

**Issue by caniggia** [JoomFish/joomfish-2.5#45]
In downloaded version from yesterday. 
When You want to Copy original to language apache reports this error and joom!Fish is processing....

[Sun Mar 18 20:39:46 2012] [error] [client XXX] script '/srv/www/vhosts/XXX/joomla/administrator/index3.php' not found or unable to stat, referer: http://XXXl/joomla/administrator/index.php?option=com_joomfish&task=manage.overview

I found reference to index3.php in administrator/components/com_joomfish/views/manage/tmpl/default.php
and administrator/components/com_joomfish/controllers/manage.php and also one statistic.php, but I don't remember localization for it.

Once You change references from index3.php to index.php everything works fine.

**Comment by klas** [comment]
Note: interface works now, but still need to check whether this function actually does anything/is still needed

**Comment by caniggia** [comment]
is not needed.

https://github.com/JoomFish/jf-future/issues/47
