### ISSUE TITLE
Manage Translations/Copy original is not neccessary and makes confuse

### ISSUE THREAD

**Issue by caniggia** [JoomFish/joomfish-2.5#47]
Hi,

Looks, that  without copying in this option all documents are visible anyway in Translations menu.
Copy original makes nothing. And for me this is correct way, I see all documents and just chose which one to translate/activate in desired language choosen by filtering.

**Comment by klas** [comment]
I checked JF 2.3 behavior and what this action does is copy all fields,  so compared to what you see in Translations where you get empty fields as translation after performing this you get unpublished, but completed translation.

In 2.5. this currently does not work, but this is different issue than this so I'm closing this issue.
