### ISSUE TITLE
Module assigned to default language is only shown for that language

### ISSUE THREAD

**Issue by quodo** [JoomFish/joomfish-2.5#53]
Klas wrote in https://github.com/JoomFish/jf-future/issues/36#issuecomment-4344085
"[Override] _Plugin goal is to make the whole Joomla behave in Joomfish way, so that the same as in 1.5. version default language (usually en-GB) behaves the same as "All languages" in core Joomla 2.5. - in a way that default language is shown when there is no translation. So it is correct that there is no All option anymore, but assigning it to "e-Gb" or whatever default site language should create the same result, if not this is a bug._"

Say you have a fresh Joomla 2.5.3 installation with sample data and you installed JoomFish jf-future (with latest commit of 1st april: 4821ac0).

When you edit the language selection module, to enable it, set it on e.g. position-0 and on "All Pages", it will only show for the language it is saved in, which is by default the default language. It will not show up for the other languages in the front end.

Also, when you open a module that was installed before JoomFish was installed, e.g. the "About Joomla!" menu module and save it it is no longer visible for All languages but only for the language it was saved for.

If I understand Klas' comment correctly this behaviour is a bug.

**Comment by klas** [comment]
With this change modules language should default to default language. 

But even before this change it was working for me on the frontend  - when I manually saved module to default language it shows in all languages for me. When saved to any other language it correctly show only for that one. Can you try again please?

Please note that you need to have overrides active, testing without it won't work.

**Comment by quodo** [comment]
The overrides plugin was and is active. The module does indeed default to the default language. The module only shows in the frontend for this default language and not the 2nd and 3rd languages (which is the problem).

I tried again, with the "old" jf-future (up to and including commit 4821ac0) on a new Joomla 2.5.3 installation and with this latest commit (c0e79cf, I checked that the changes of your commit are in the files that I install). 

After (a fresh/new) installation of JoomFish the "JoomFish language selector"-module shows "All" for the "Language", however, after I save it it is in the default language (en-GB in my case). I have to save the module to set it to published, on a position ("position-0" on Joomla's default template Beez) and for "All pages". Automatically "Language" is no longer set to "All" but to the default language and the module in the frontend only shows for the default language.

System details
PHP 5.2.9, Apache server on Windows (Win32), MySQL 5.1.33, mysqli driver, error reporting set to maximum and debug on, Joomla 2.5.3 with en-GB as default and nl-NL and de-DE installed, Mozilla Firefox as browser.

_(Klas: I'll send you details of the site where you can take a look yourself)_

**Comment by quodo** [comment]
This solved it! Thank you!

Now I can save modules, which then are saved to the default language, and they appear in all languages like "we" want JoomFish to behave.
