### ISSUE TITLE
submenu items don't show in 2nd language when their parent is translated

### ISSUE THREAD

**Issue by quodo** [JoomFish/joomfish-2.5#54]
With Joomla's sample data there is a frontend menu "About Joomla" where the entry "Using Joomla!" has three submenu items: Using Extension, Parameters, Getting Help. When you click "Using Joomla" the submenu items are shown.

Now translate the menu item "Using Joomla!" is into a second language, e.g. dutch (nl-NL). When you set the frontend to this second language with the language selector and choose the translated "Using Joomla" menu item, the menu no longer shows its submenu items.

Probable reason: the original menu item had id 280 in table jos_menu, the translated menu item has a new menu id (in my case 480) and thus the submenu items with their parent_id 280 are not shown.

Joomla 2.5.3, PHP 5.2.9, MySQL 5.1.33, Mozilla Firefox
JoomFish jf-future with latest commit 4821ac0

p.s. Thought it was worth its own issue, but I've mentioned it here as well: https://github.com/JoomFish/jf-future/issues/36#issuecomment-4236122 in the "native vs joomfish"-question.

**Comment by klas** [comment]
Fixed as part of #55 fixes

**Comment by quodo** [comment]
Solved! Thanks!
