### ISSUE TITLE
Error 500 when saving translation: cannot delete from "jos_dbcache"

### ISSUE THREAD

**Issue by quodo** [JoomFish/joomfish-2.5#56]
**Reproduce**
Backend > Components > JoomFish > Translation > [Set Content Element to (for example) Menu] and [set Languages to the 2nd language] > [Click any menu item and edit it] > Click Save.

Result
Translation is saved, however, page shows:
  500 - An error has occurred.
  JDatabaseMySQLi::query: 1146 - Table 'joomla_development_joomla25joomfish.jos_dbcache' doesn't exist SQL=DELETE FROM `jos_dbcache`

**System**
Joomla 2.5.4, PHP 5.2.9, Database 5.1.33, mysqli, apache server on windows.
Latest pull request on jf-future that I installed: 8d5b5efad8 on 20 april 2012.

**Notes**
I don't have the table jos_dbcache. 
This table can be created in function setupDB in file /admin/classes/JCachStorageJFDB.php. It's called at three places
- 2x: function checkDBCacheStructure in /admin/helpers/controllerHelper
- function gc: /admin/classes/JCacheStorageJFDB.php

The function where this error stems from is cleanCache() in /admin/classes/JCacheStorageJFDB.php on line 291 (https://github.com/JoomFish/jf-future/blob/master/admin/classes/JCacheStorageJFDB.php#L291). This cleanCache() functions is called from the contstruct of this class on line 89 (https://github.com/JoomFish/jf-future/blob/master/admin/classes/JCacheStorageJFDB.php#L89).

**Comment by quodo** [comment]
Now I've got a jos_dbcache table too! (after re-installation)

**Comment by klas** [comment]
good :) thnx :)
