### ISSUE TITLE
Backwards routing of menu items set to default language is broken

### ISSUE THREAD

**Issue by klas** [JoomFish/joomfish-2.5#57]
When menu item is set to default language, langswitcher creates a correct URL, but reverse routing (after item is clicked) does not work (route is incorrectly parsed)

**Comment by klas** [comment]
Turns out anything not \* or current language was broken due to another harcoded joomla value (\* in this case).

**Comment by mouttaqui** [comment]
I used the last changes you made ​​but now the menu is not translated

**Comment by klas** [comment]
Have you translated a menu trough Joomla or trough Joomfish interface?

**Comment by mouttaqui** [comment]
Joomfish interface

**Comment by klas** [comment]
Ok, thnx, I will re-check, seemed to be working for me.

Please let me know if you downloaded joomfish yesterday as I made some changes during the night, could be I missed some file...

**Comment by mouttaqui** [comment]
I downloaded all the files you have changed

**Comment by klas** [comment]
I rechecked and it works ok after re-installation on my test server. Can you please confirm you followed this instructions https://github.com/JoomFish/jf-future/wiki/Installation-instructions ?

In short, you need to download zip file from github,  uninstall joomfish admin component (this will uninstall the whole package) and reinstall from zip you downloaded. Post-installation instructions are on the wiki page above.

If it is still not working after the reinstall, please give us exact instructions on how to replicate this issue including your php and mysql versions and joomla version.

**Comment by mouttaqui** [comment]
thank you
I reinstalled the component joomfish and I have no problem except that I have detected another bug

I developed a component that can bring a list element, when I change language, the list is displayed very well, but when I plug in an element and I try to change the language, I falls on a 404 page and the URL of that page changes
