### ISSUE TITLE
The sample menu item "Display Modules" of the type "Articles > Category List" results in an Error 500

### ISSUE THREAD

**Issue by quodo** [JoomFish/joomfish-2.5#60]
**Problem**
I'm translating each and every item in the "About Joomla" module from the sample data. For the "Display Modules"  (About Joomla! module: Using Joomla > Using Extensions > Modules >  Display Modules) I get a 500 Error. Both in the default language (en-GB) and the menu item translated in the second language (nl-NL)

**Info**
The "Display Modules" is of the menu item type "Articles > Category List".
The non-SEF URL (according to the info when editing the Menu Type) is index.php?option=com_content&view=category&id=66.

**Error message**
JDatabaseMySQLi::query: 1054 - Unknown column 'c.published' in 'field list' SQL=SELECT a._, c.published AS c_published, CASE WHEN CHAR_LENGTH(a.alias) THEN CONCAT_WS(':', a.id, a.alias) ELSE a.id END as slug, CASE WHEN CHAR_LENGTH(c.alias) THEN CONCAT_WS(':', c.id, c.alias) ELSE c.id END as catslug,DATE_FORMAT(a.date, "%Y-%m-%d") AS created,CASE WHEN a.created_by_alias > ' ' THEN a.created_by_alias ELSE ua.name END AS author FROM `jos_weblinks` AS a LEFT JOIN jos_users AS ua ON ua.id = a.created_by LEFT JOIN jos_users AS uam ON uam.id = a.modified_by WHERE a.access IN (1,1) AND a.state = 1 AND a.state != -2 AND a.language in ('en-GB','_','en-GB') ORDER BY ordering asc

**Call stack**
    Function    Location
1   JSite->dispatch()   ...\index.php:42
2   JComponentHelper::renderComponent()     ...\includes\application.php:198
3   JComponentHelper::executeComponent()    ...\libraries\joomla\application\component\helper.php:357
4   require_once()  ...\libraries\joomla\application\component\helper.php:388
5   JController->execute()  ...\components\com_content\content.php:18
6   ContentController->display()    ...\libraries\joomla\application\component\controller.php:754
7   JController->display()  ...\components\com_content\controller.php:77
8   ContentViewCategory->display()  ...\libraries\joomla\application\component\controller.php:715
9   JHtml::_()  ...\components\com_content\views\category\view.html.php:97
10  JHtml::call()   ...\libraries\joomla\html\html.php:103
11  call_user_func_array()  ...\libraries\joomla\html\html.php:222
12  JHtmlContent::prepare()  
13  JDispatcher->trigger()  ...\libraries\joomla\html\html\content.php:42
14  JEvent->update()    ...\libraries\joomla\event\dispatcher.php:161
15  call_user_func_array()  ...\libraries\joomla\event\event.php:71
16  plgContentLoadmodule->onContentPrepare()  
17  plgContentLoadmodule->_loadmod()    ...\plugins\content\loadmodule\loadmodule.php:87
18  JDocumentRendererModule->render()   ...\plugins\content\loadmodule\loadmodule.php:130
19  JModuleHelper::renderModule()   ...\libraries\joomla\document\html\renderer\module.php:106
20  include()   ...\libraries\joomla\application\module\helper.php:175
21  modWeblinksHelper::getList()    ...\modules\mod_weblinks\mod_weblinks.php:15
22  WeblinksModelCategory->getItems()   ...\modules\mod_weblinks\helper.php:78
23  JModelList->getItems()  ...\components\com_weblinks\models\category.php:81
24  JModelList->getStart()  ...\libraries\joomla\application\component\modellist.php:128
25  JModelList->getTotal()  ...\libraries\joomla\application\component\modellist.php:265
26  JModel->_getListCount()     ...\libraries\joomla\application\component\modellist.php:231
27  JFDatabase->query()     ...\libraries\joomla\application\component\model.php:336
28  interceptDB->query()    ...\plugins\system\jfdatabase\jfdatabase_inherit.php:689
29  JDatabaseMySQLi->query()    ...\plugins\system\jfdatabase\intercept.jdatabasemysqli.php:276
30  JError::raiseError()    ...\libraries\joomla\database\database\mysqli.php:396
31  JError::raise()     ...\libraries\joomla\error\error.php:251

**Comment by klas** [comment]
Turns out this is joomla bug, the same thing happens with debug mode and no joomfish installed

**Comment by klas** [comment]
more info: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=28483
