### ISSUE TITLE
Translate Menu will make it double

### ISSUE THREAD

**Issue by mcwolf00** [JoomFish/joomfish-2.5#62]
When translate a menu from en to zh. Joomfish will create a new menu with chinese. Click chinese menu or default menu will go to the same menu page which contains both chinese menu items and default menu items.

**Comment by quodo** [comment]
Do you still have that problem with Klas' latest commit 2b077be08e (see list on https://github.com/JoomFish/jf-future/commits/master)? I had the same problem before, but for me it was fixed with that commit.

**Comment by klas** [comment]
also https://github.com/JoomFish/jf-future/wiki/Installation-instructions - take a look at "Check Joomfish system plugins ordering numbers" part.

**Comment by klas** [comment]
I will close this issue as we can't confirm it with latest revision. if this is still an issue please let us know with more detailed data on how to reproduce it.
