### ISSUE TITLE
with JoomFish-jf-future-alpha5-5-geef2efa.zip front and back end crashs

### ISSUE THREAD

**Issue by alainroger** [JoomFish/joomfish-2.5#79]
Hi,

I faced several issues with jf-future 2.5 alpha:
1. with new joomla 2.5.4 user registration raises a warning message and doesn't finish the registration process.
here is the warning message:
Registration failed: Registration failed: Unknown column 'Array' in 'field list' SQL=INSERT INTO `j25_user_usergroup_map` (`user_id`,`group_id`) VALUES (49, Array)

==> solution: disable the plug-in "Joomfish - Database Abstraction Layer"
1. after update of jf-future to latest version (10.06.2012 called "JoomFish-jf-future-alpha5-5-geef2efa.zip"), i faced a new problem.
   just after installation of your package, front end displays a white/blank page.
   after disabling the same plug-in as above. front end works well, but back end displays white/blank page

if this plug in is enable, front end displays white/blank page and back end side works well again.

HTH

Alain R.

PS: i sent a post at: http://www.joomfish.net/forum/viewtopic.php?f=48&t=11465

**Comment by klas** [comment]
I can confirm the first issue, but backend/frontend works fine for me. As quodo reports on the forum problem is probably that in case that database plugin is disabled you will get fatal error, which is an issue by itself, you should be receiving a message that you need to publish a plugin.
