### ISSUE TITLE
Error on image upload via image button.

### ISSUE THREAD

**Issue by ramchos** [JoomFish/joomfish-2.5#80]
I get these errors  when i upload image through the image button of the editor, though images upload normally it;s necessary to reopen the window to upload next image.

Warning: Missing argument 3 for plgSystemJFDatabase::onContentBeforeSave() in C:\xamppp\htdocs\sitename\plugins\system\jfdatabase\jfdatabase.php on line 253

Fatal error: Call to undefined method JObject::getTableName() in C:\xamppp\htdocs\sitename\plugins\system\jfdatabase\jfdatabase.php on line 260

All plugins are published.

**Comment by klas** [comment]
First issue is actually a Joomla problem, see http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_id=8103&tracker_item_id=28654

But as that function is not used anyway I commented it out, so both problems should be fixed now
