### ISSUE TITLE
Featured Articles not showing

### ISSUE THREAD

**Issue by valandis** [JoomFish/joomfish-2.5#83]
Various articles already written and published as Featured are not showing in the Frontend (Featured Articles Layout).

---

Joom!Fish installed on Joomla! 2.5.6.

System state under Joom!Fish Control Panel:
All Green except: PHP VersionCurrent setting: 5.2.17 DOES NOT equal optimal setting 5.3.0

**Comment by klas** [comment]
Can you give us a little more info what is the language for those articles - are they set to default language or something else? Aslo, which sql driver are you using? (mysqli, msyl..) ?

Thing is everything works ok on my test server, I'm testing on joomla sample data with featured articles on the frontend

**Comment by klas** [comment]
Also, are you getting any errors when you set error reporting in joomla to maximum? 
Have you followed steps described in install instructions https://github.com/JoomFish/jf-future/wiki/Installation-instructions ?

Sorry for asking all this questions, but this is the only way to find the difference in our setups that leads to this.

**Comment by valandis** [comment]
I double-checked the installation steps. Everything's done this way, except that I installed the 2 extra languages (Greek and German) before I install JoomFish. English is the default language by the way.

---

Additional info:
- the database driver is the recommended one mysqli
- Joomla's core multilanguage plugins/modules are disabled
- JoomFish's own plugins are enabled and in the correct order
- languages are correctly configured and activated in JoomFish
- I turned on Debug System and Error Reporting to Maximum (no visible errors in the Frontend/Backend)

---

Something I haven't mentioned before, this is not a clean Joomla install. Joomla's installation was made after transferring an old site's content by using jUpgrade (no errors). I have also installed some other 3rd party extensions, though they don't interfere in the Frontend in the views where I discovered the issues. If you need me to check something else let me know.

**Comment by klas** [comment]
I doublecheckeked and I'm unable to replicate this using fresh joomla install and sample data neither on php 5.2 or 5.3. (on windows). Will try on other systems tomorrow.

Have you by any chance had joomfish installed on you old site?

**Comment by quodo** [comment]
Issue 83:
"Various articles already written and published as Featured are not showing in the Frontend (Featured Articles Layout)."

Summary: cannot replicate this issue.

Test system:
JoomFish for J25 b52f83fd86a13139bf1f7eb65e05d8dd8ac52e82
Joomla 2.5.4/2.5.6 (Fresh 2.5 installation with upgrade from 2.5.x to 2.5.4 and then 2.5.6)
PHP 5.2.9, mysqli, Apache 2.2.1 on Windows, Mozilla Firefox 12
Default language english (en-GB), second language dutch (nl-NL)

Test 1:
Joomla Sample data has menu items of the "Menu Item Type" "Articles » Featured Articles" via 
- Using Joomla > Using Extensions > components > Content Component > Featured Articles
- Using Joomla > Using Extensions > Templates > Beez 2/Beez 5/Atomic > Home Page Beez 2 /Beez 5/Atomic (respectively)

These articles do show the translated content okay.

Test 2:
Added a new article, only in default language, and set it to featured. This does show in english and dutch. Translated it with JoomFish and now I have the enligsh article in english and the dutch article in dutch.

Valandis, I'm curious: what happens if you create a new article and "feature" it? Does that show? E.g. the featured articles that won't show, were they all present in your Joomla 1.5.x installation that you upgraded with jUpgrade?
What was the JoomFish version on your Joomla 1.5.x installation before you upgraded?

**Comment by valandis** [comment]
Yes I did have JoomFish installed on the old site (v2.0.2), but no DB tables were migrated by using jUpgrade. I checked the database and the tables of JoomFish 2.5 #__jf_content and jf_languages_ext are both empty, only jf_tableinfo and jf_translationmap contain data.

The featured articles that don't get displayed at all (as well as all category views blog, list etc) were all present on the old Joomla installation.

I created a new test article published it as featured and a menu item pointing at it; when clicking on the menu item it shows the article, but when in featured/category view nothing is being displayed. By the way I can't change language to "All" for any menu items or articles, is this a bug of JoomFish (by the override plugin)?

**Comment by valandis** [comment]
Update: I uninstalled JoomFish 2.5, and Featured Articles still not showing(!) if Joomla's system plugin "Language Filter" is enabled.

After I deactivate "System - Language Filter" plugin, et voilà, the Featured Articles are all there as well as all Category Lists. What has just happened? Who's to blame now, Joomla, jUpgrade or JoomFish? What kind of "bug" is this, I really don't get it.

**Comment by klas** [comment]
Was this working before you installed Joomfish? Joomfish does not change original articles or files, so after you deinstalled the component and together with it all the plugins and the language switcher module, everything should be as it was before. 

Only thing that comes to my mind is - if you saved any of the original articles after you installed JF they would not be marked as \* (All languages), they would have default language assigned to them.

**Comment by klas** [comment]
From what we know at this point this is JUpgrade issue, not Joomfish, closing for now.

**Comment by valandis** [comment]
I have to be honest with you, after migrating the site with jUpgrade I immediately installed several extensions, languages and JoomFish as well. I haven't tested the Category Lists and Featured Articles if they worked before I install JoomFish. If JoomFish after successful uninstall removes all files and changes it does then it must be some kind of Joomla, or jUpgrade error.

I have all articles set to ALL languages, after enabling the "System - Language Filter" plugin on the Frontend Featured Articles and Category Lists are totally empty -no articles whatsoever. When this plugin is disabled everything is displayed correctly.

**Comment by valandis** [comment]
Regarding this issue again I want to bring something new in and more specifically:

I installed the new version of jUpgrade v2.5.2 and tried a migration from J1.5 to J2.5 again. This time I didn't install any extensions at all, just previewed the site and saw the Featured Articles were displayed just fine. Then I installed the latest JoomFish version -without adding languages whatsoever- and saw that the Featured Articles disappeared from view. After uninstalling JoomFish the Featured Articles were back again.

Do you think it is a jUpgrade issue?
