### ISSUE TITLE
Editing Default Menu Item fails

### ISSUE THREAD

**Issue by valandis** [JoomFish/joomfish-2.5#84]
After installing Joom!Fish the editing of the default menu item (homepage) fails after trying to save it with the following message:

Save failed with the following error: The Language parameter for this menu item must be set to 'All'. At least one Default menu item must have Language set to All, even if the site is multilingual.

Though changing the Language to All is not possible, because the only available options are the published languages (in my case English, German and Greek).

**Comment by tdzweb** [comment]
I have also noticed this. You need to set default page for the original language before you install Jf. Kind of annoying if you forget, because you can never get rid of it after that :)

**Comment by ghost** [comment]
is it final? or this will be fixed later?

**Comment by tdzweb** [comment]
Sorry I dont work here I am just visiting, howeverI suspect it is undecided. Take a look at this discussion further down: https://github.com/JoomFish/jf-future/issues/36
It seems to be a struggle between the usual suspects: security, design and functionality :)

**Comment by valandis** [comment]
yes it seems there hasn't been a solution to this issue yet...

**Comment by klas** [comment]
Hi,  it is just a small code change but due to the unfortunate way Joomla is coded we need to load anther class override to fix this, I'll add this today

**Comment by valandis** [comment]
Thank you Klas. By the way regarding that -closed- issue about the Featured Articles not showing, can you please check it again? I posted a comment back there https://github.com/JoomFish/jf-future/issues/83#issuecomment-7006517 regarding that issue. It seems the new version of jUpgrade didn't help (or maybe it's a JoomFish issue).

**Comment by klas** [comment]
Fixed in c53850d861f8b8b407053278f1996d9b5b818c7b ,  
closing
