### ISSUE TITLE
Category List/Blog views not showing any articles

### ISSUE THREAD

**Issue by valandis** [JoomFish/joomfish-2.5#85]
No articles are showing under a menu item that points to the Category (list/blog view), where these articles are published.

On the contrary, menu items that point to a Single article, this article is displayed.

---

Joom!Fish installed on Joomla! 2.5.6.

System state under Joom!Fish Control Panel:
All Green except: PHP VersionCurrent setting: 5.2.17 DOES NOT equal optimal setting 5.3.0

**Comment by klas** [comment]
Hi, the same as with #83, everything works ok here, so please give us more details on your setup (as described in #83 ) so we can replicate this.

**Comment by valandis** [comment]
My reply with further details here: https://github.com/JoomFish/jf-future/issues/83

**Comment by klas** [comment]
The same as #83, from what we know at this point this is JUpgrade issue, not Joomfish, closing for now.
