### ISSUE TITLE
Translation of the label path of menulinks not working

### ISSUE THREAD

**Issue by sju10544** [JoomFish/joomfish-2.5#86]
Hi all,

I created a menulink or menu item alias (from the system links) in my main menu in Germany on this site: http://www.florida-scout.com.

After that I made all the neccessary entries and this works perfect in German (http://www.florida-scout.com/de/einkaufen)

Then I went to Joomfish and tried to translate this menulink in English. But unfortunately the problem is that the label path is not correct translated. Instead of the correct translation of the English menus / categories, the first menu comes up in German, the next following is in English. So when I click then after saving this on my menu, then comes this:

Error loading component: , 1
Component not found
Error loading component: , 1

and the path is http://www.florida-scout.com/en?Itemid=257 (this ID is the German original one) instead of this expected one:

http://www.florida-scout.com/activities/shopping

To make it easier I have made a screenshot of the Joomfish translation menu also here: http://www.joomfish.net/forum/viewtopic.php?f=48&t=11505&p=39175#p39175

I guess this is a bug, so any help or ideas would be great.

Thanks and best regards

Jens

System Details: Linux Server 2.6.32-5-amd64 #1 SMP Sun May 6 04:00:17 UTC 2012 x86_64
Datenbankversion: 5.1.63-0+squeeze1
Datenbankzeichensatz: utf8_general_ci
PHP-Version: 5.3.3-7+squeeze13
Webserver: Apache
PHP-Interface für den Webserver: cgi-fcgi
Joomla!-Version:    Joomla! 2.5.6 Stable [ Ember ] 19-June-2012 14:00 GMT
Joomla!-Plattform-Version: Joomla Platform 11.4.0 Stable [ Brian Kernighan ] 03-Jan-2012 00:00 GMT
Browsererkennung: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:13.0) Gecko/20100101 Firefox/13.0.1

JoomFish for Joomla 2.5 version: JoomFish-jf-future-alpha6-7-gb52f83f.zip

**Comment by klas** [comment]
Hi, I just tried to reproduce this and alias menus seem to work ok with the latest version. Can you try if issue is resolved using latest version from github? Also please check that you followed installation instructions

**Comment by sju10544** [comment]
Hi Klas,

thanks for the answer. But due to too much respons times and development of Joomfish for Joomla versions 2.5.x I decided to use GTranslate for our homepages…

Jens
