### ISSUE TITLE
Translation of RokNavMenu module fails

### ISSUE THREAD

**Issue by tdzweb** [JoomFish/joomfish-2.5#87]
I have no idea if this is a Rocketheme issue or Joomfish issue. The error is as follows:
Theme Options    Fatal error: Class 'RokSubfieldForm' not found in C:\inetpub\wwwroot\joomla25\modules\mod_roknavmenu\fields\themeoptions.php on line 56

**Comment by tdzweb** [comment]
Apparently a class definition was missing. Probably because Joomfish does not load all the libraries necessary. I suppose this is because the RokNavMenu is coded with a structure that may be incompatible with Joomfish?

In any case, I added a require_once ... to make sure the class file was loaded and that fixed the problem (for now).

**Comment by klas** [comment]
Hi,

calling necessary includes from extension itself is  the only way this problem can be fixed - as it is not a big change perhaps you can ask RokNAvMenu makers to include this change in next release.

**Comment by tdzweb** [comment]
I will do so.
