### ISSUE TITLE
Language Switcher uses translated alias for original category

### ISSUE THREAD

**Issue by tdzweb** [JoomFish/joomfish-2.5#89]
When viewing items by categories (tested for both articles and weblinks) the Joomfish Language Switcher will shift to use the translated category alias for both (only tried with two languages so far). Thus when you switch back to the original language you get a 404 error (or "Weblink not found"). This does not happen in the detail/item view, only for lists.

Test site (note, registration is enabled. I will give manager access if you ask):
Joomla version 2.5.6
Joomfish build: JoomFish-jf-future-alpha6-8-g743b4aa
http://dev1.tdzwebdesign.no/joomla25/j256-a/

**Comment by tdzweb** [comment]
Small update: The description above is not entirely accurate. There is something wrong with the switcher when viewing articles and web links (and probably all other content) in their respective detail views. I think the URL generated by the switcher uses the alias for the current language on both (all) flags, but the rest of the URL points to the correct language, causing a 404 error when switching.

**Comment by klas** [comment]
Hm, I have trouble reproducing this - I wonder whether this is related to double subfolder that you have in the base URL /joomla25/j256-a/

**Comment by tdzweb** [comment]
I just reproduced it on my localhost using only a single subfolder (http://localhost/joomla25). It seeminly only occurs when I drill down the categories from a menu item of type Category/List All Categories.

Perhaps the problem is this. When I translate one category, the translated cateogory is always created as a sibling of the original. Therefore the translation does not preserve the category hierarchy. This is a bit of a picle it seems, because to fix this JoomFish cannot allow a category tree to be partially translated. I think JoomFish needs to automatically mirror the entire original language category tree.

**Comment by klas** [comment]
Ok, thnx, now I managed to reproduce it. Router somehow thinks generated id is article id, instead of category one.
