### ISSUE TITLE
Google Translate no longer available

### ISSUE THREAD

**Issue by quodo** [JoomFish/joomfish-2.5#9]
(From old thread: https://github.com/JoomFish/jf-future/pull/1)
**Quodo:**
F - Tried "Translated powered by Google" (nice feature!)
Shows alert box: "Please use Translate v2. See http://code.google.com/apis/language/translate/overview.html" --> API v1 is no longer available per December 1, 2011.
**GeraintEdwards** replied
F. Klas is looking at this.

Update: Button no longer works. The link http://code.google.com/apis/language/translate/overview.html now has this information:
_Important: Google Translate API v2 is now available as a paid service only, and the number of requests your application can make per day is limited. As of December 1, 2011, Google Translate API v1 is no longer available; it was officially deprecated on May 26, 2011. These decisions were made due to the substantial economic burden caused by extensive abuse. For website translations, we encourage you to use the Google Website Translator gadget._
Where information on the paid service is found here: http://code.google.com/apis/language/translate/v2/pricing.html.

It seems that this service is no longer available for free. Does this mean the button, and the code behind it should be removed?

**Comment by klas** [comment]
This has been fixed in JF-core (implemented V2 API), need to port it to JF-Future, I waited for code merge of branches.

**Comment by akempkens** [comment]
@Klas you mean code merge of jf-core and jf-future?

We can also re-apply your patch may be. This way we can keep on moving on with jf-future as the main branch after 2.2.3 is released.

**Comment by klas** [comment]
@Alex - yes, patching jf-future with changes from jf-core is what I meant. Was hard to implement it before jf-future branches were merged together as in Geraints branch popups were not working and so hard to test.

**Comment by klas** [comment]
Fixed / done
