### ISSUE TITLE
Article Options Paramters are not displaying

### ISSUE THREAD

**Issue by chavansoft** [JoomFish/joomfish-2.5#90]
Article Options Paramters are not displaying any dropdowns. please advice

**Comment by klas** [comment]
Hi, can you please explain in more detail, what is meant by "Article Options Parameters are not displaying any dropdowns" - I cannot confirm this on my test installation using latest JoomFish-jf-future-alpha6-10-g38233b1.zip.

Also please give us basic information about your system:
- JF version installed
- Mysql driver being used (Site->global configuration->Server tab->Database settings->Database Type)
- Complete output of Site->System information->System information tab

**Comment by klas** [comment]
Do you mean article parameters in menus - jsut fund out that none of parameters dropdowns work in menus (but is ok when translating article itself).

**Comment by JohnDelay2** [comment]
Hi there,

he may meant: If you go to the Control Panel an click on the Options-button in the upper right corner, you´ll get a light box with 2 tabs. On the 2nd tab called "Permissions" all the dropdowns to manage the permission settings for the user groups are missing.

My system: Joomla v. 2.5.8 with jf-future v. 2.5.1

Cheers, John

**Comment by akempkens** [comment]
This can be related to the fact that we have not yet defined any permission scheme for JoomFish. Will double check.
