### ISSUE TITLE
Translate page is destryoed after upgrade

### ISSUE THREAD

**Issue by sju10544** [JoomFish/joomfish-2.5#93]
After deleting the old version and uploading the newest version of Joomfish (JoomFish-jf-future-alpha7-1-g0e67b44) the page for the tranlation process doesn't work (components->Joomfish->Translation->menue (for example).

There are only the first two lines visible (no icons etc.). Looks like the program is missing some forms, library content etc.

My system:

System Details: Linux Server 2.6.32-5-amd64 #1 SMP Sun May 6 04:00:17 UTC 2012 x86_64
Datenbankversion: 5.1.63-0+squeeze1
Datenbankzeichensatz: utf8_general_ci
PHP-Version: 5.3.3-7+squeeze13
Webserver: Apache
PHP-Interface für den Webserver: cgi-fcgi
Joomla!-Version: Joomla! 2.5.6 Stable [ Ember ] 19-June-2012 14:00 GMT
Joomla!-Plattform-Version: Joomla Platform 11.4.0 Stable [ Brian Kernighan ] 03-Jan-2012 00:00 GMT
Browsererkennung: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:13.0) Gecko/20100101 Firefox/13.0.1

Jens

**Comment by klas** [comment]
Hm, seems to work ok for me, are you getting any errors?

**Comment by sju10544** [comment]
Hi Klas,

thanks for the reply.

No, unfortunately I got no errors. But you can find in the attachment a screenshot of the (partial) page.

Have tried to install the latest Joomfish version on another page before I posted the error on GitHub. But just the same thing...

Have another question: do you know when we can expect the migration tool from Joomla 1.5 Joomfish tables to migrate the "old" stuff to a Joomla 2.5 site?

It's really important and I (yes I know, many of us) are waiting to get our old pages productive with J2.5.

Thanks and kind regards

Jens

-----Ursprüngliche Nachricht-----
Von: Klas [mailto:reply@reply.github.com] 
Gesendet: 16.July 2012 13:59
An: sju10544
Betreff: Re: [jf-future] Translate page is destryoed after upgrade (#93)

Hm, seems to work ok for me, are you getting any errors?

---

**Comment by sju10544** [comment]
Hi Klas,

thanks for the reply.

No, unfortunately I got no errors. But you can find in the attachment in my E-Mail (just send) a screenshot of the (partial) page.

Have tried to install the latest Joomfish version on another page before I posted the error on GitHub. But just the same thing...

**Comment by klas** [comment]
Hi, screenshot did not get posted, please upload is somewhere

**Comment by sju10544** [comment]
Hi Klas,

can only attached the screenshot with this E-Mail, unfortunately not in GitHub. So another try :-)

Jens

-----Ursprüngliche Nachricht-----
Von: Klas [mailto:reply@reply.github.com] 
Gesendet: 17.July 2012 18:53
An: sju10544
Betreff: Re: [jf-future] Translate page is destryoed after upgrade (#93)

Hi, screenshot did not get posted, please upload is somewhere

---

**Comment by klas** [comment]
if email is the only way, please forward it to klas.berlic AT gmail.com

**Comment by klas** [comment]
Hi, thnx, error message you sent to me cleared things - problem was in camel cased file names, things should work on unix based systems after fa5c6c0abe6dc105fc5db6d7d8ab43001bed48b3, let me know if this is not the case
