### ISSUE TITLE
K2 extra field

### ISSUE THREAD

**Issue by ghost** [JoomFish/joomfish-2.5#95]
Hi,

Your component works fine but, when i translate an item in k2, that i translate his extrafield too, then i click to save (not on save and close). The translation of my extra field dispear, it's a big problem :s.

**Comment by ghost** [comment]
this problem is still unresolved?

**Comment by ghost** [comment]
When i install your package then i install k2 i have tthis message : 

 K2 Content Elements for Joom!Fish were not copied to the related folder, because Joom!Fish was not found on your sytem.

**Comment by pollux007** [comment]
For the message:
K2 Content Elements for Joom!Fish were not copied to the related folder, because Joom!Fish was not found on your sytem

Copy the folder administrator\components\com_joomfish\contentelements from joomla 1.5 to the same folder in joomla 2.5

**Comment by klas** [comment]
This second problem is solved now, we moved contentelements folder to libraries, I re-added an empty contentelements folder in administrator for backwards compatibility. Elements are read from both locations.

**Comment by klas** [comment]
I just looked up what is happening and this is something that needs to be fixed on  K2 side, joomfish is correctly displaying fields according to xml definition.
