### ISSUE TITLE
Class JFForm not found 

### ISSUE THREAD

**Issue by opignon** [JoomFish/joomfish-2.5#96]
hi,
i've found a bug in the naming of some files in the package alpha7 :
Class JFForm not found j 2.5
if you replace UPPERCASE with lowercase in filenames in folder : joomfish/form
 it resolve it

hope it helps

regards

Olivier

**Comment by klas** [comment]
Hi, thnx for the report. Issue was fixed in the fa5c6c0abe6dc105fc5db6d7d8ab43001bed48b3 some time ago
