### ISSUE TITLE
Translate error

### ISSUE THREAD

**Issue by erwinds** [JoomFish/joomfish-2.5#97]
hi,

I habe a problem with translate only in (menus or contents)
Fatal error: Call to protected method JFormField::getName() from context 'TranslateParams_xml' in E:\wamp\www\erwin-j25\libraries\joomfish\translateparams\xml.php on line 114

in (categories, contacts, modules or somthing else) it's ok

Version:
Joomla 2.5.6
JoomFish-jf-future-alpha7-6-gfa5c6c0

**Comment by klas** [comment]
Hi,

can you explain exactly what type of menu (which component & which view) you have set as Home (or as any menu that crates this problems). or are you getting this on all menus?

Also please try using latest version.

**Comment by erwinds** [comment]
Hi,

I have this problem on the component menus and content. I  think  the problem is with the params.
I use the latest verion,

**Comment by erwinds** [comment]
Hi,

I have this problem on the component menus and content. I  think  the problem is with the params.

I use the latest verion, 

JoomFish-jf-future-alpha7-6-gfa5c6c0

Tot later,

Erwin

Van: Klas [mailto:notifications@github.com] 
Verzonden: woensdag 22 augustus 2012 16:29
Aan: JoomFish/jf-future
CC: erwinds
Onderwerp: Re: [jf-future] Translate error (#97)

Hi,

can you explain exactly what type of menu (which component & which view) you have set as Home (or as any menu that crates this problems). or are you getting this on all menus?

Also please try using latest version.

—
Reply to this email directly or view it on GitHub https://github.com/JoomFish/jf-future/issues/97#issuecomment-7935901 . 

  https://github.com/notifications/beacon/Jshd8sI44GVrKZBvymxqKDSB_op0NPBsvwhRZildond2mFGJ7vAUjm0Pk08F8SY5.gif

**Comment by klas** [comment]
What I'm asking is whether you have this problem on all menus or just on specific ones - e.g menu can be liked to com_content, k2, some gallery etc. Are you usingn any non-standard backend templates?   Thing is I'm unable to reproduce this error so it must be something specific to your installation.

**Comment by erwinds** [comment]
Hi,

I’m use menu.xml and content.xml

And template is from RocketTheme

Van: Klas [mailto:notifications@github.com] 
Verzonden: woensdag 22 augustus 2012 22:23
Aan: JoomFish/jf-future
CC: erwinds
Onderwerp: Re: [jf-future] Translate error (#97)

What I'm asking is whether you have this problem on all menus or just on specific ones - e.g menu can be liked to com_content, k2, some gallery etc. Are you usingn any non-standard backend templates? Thing is I'm unable to reproduce this error so it must be something specific to your installation.

—
Reply to this email directly or view it on GitHub https://github.com/JoomFish/jf-future/issues/97#issuecomment-7947992 . 

  https://github.com/notifications/beacon/Jshd8sI44GVrKZBvymxqKDSB_op0NPBsvwhRZildond2mFGJ7vAUjm0Pk08F8SY5.gif

**Comment by erwinds** [comment]
Hi,

I’m use menu.xml and content.xml

And template is from RocketTheme

**Comment by klas** [comment]
Hi,

I'm asking about BACKEND (administrator) template.

We need to figure out why this happens to you and not to everyone else.

**Comment by erwinds** [comment]
The backend template = Bluestork

Van: Klas [mailto:notifications@github.com] 
Verzonden: vrijdag 7 september 2012 15:22
Aan: JoomFish/jf-future
CC: erwinds
Onderwerp: Re: [jf-future] Translate error (#97)

Hi,

I'm asking about BACKEND (administrator) template.

We need to figure out why this happens to you and not to everyone else.

—
Reply to this email directly or view it on GitHub https://github.com/JoomFish/jf-future/issues/97#issuecomment-8364996 . 

  https://github.com/notifications/beacon/J6T91GIPIyhU-8ti4GCGP7hCchZG4A5O2pE-yE8FCbsaFnfrHynGY1fQ2hhnMm6i.gif

**Comment by armand1981** [comment]
I can see no solution and i have this problem also!

**Comment by klas** [comment]
Which PHP version do you use? Seems this is related to early PHP 5.2 versions (e.g. 5.2.4)

**Comment by armand1981** [comment]
Ah: Current setting: 5.2.5 DOES NOT equal optimal setting 5.3.0

Op 31 jan. 2013, om 11:56 heeft Klas notifications@github.com het volgende geschreven:
