### ISSUE TITLE
Contentelements folder is not installed

### ISSUE THREAD

**Issue by tdzweb** [JoomFish/joomfish-2.5#99]
**In JoomFish-jf-future-alpha7-12-gf1018f9.zip:**
It appears that the contentelements folder is not installed. Might be just a glitch in the manifest, but it appears to only contain the index.html in the package.

**The following warning is thrown by Joomla**

```
JFolder: :files: Path is not a folder. Path: [BASE]\administrator\components\com_joomfish\contentelements
```

**The following warning is thrown by PHP**

```
Warning: Invalid argument supplied for foreach() in [BASE]\libraries\joomfish\manager.php on line 191
```

**Comment by klas** [comment]
This should be fixed in latest version, folder was missing from manifest
